name: Keep Render Awake

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping backend
        run: curl https://final-project-4yy7.onrender.com/health
